(when (not (package-installed-p 'smex)) (package-install 'smex))
(smex-initialize)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-majore-mode-commands)
(global-set-key (kbd "C-c C-c M-x") 'smex-extended-command)
(provide 'setup-smex)
